window.Admin = (() => {
  let config=null,responses=[],dashRole='Overall';
  const $=id=>document.getElementById(id), E=Core.esc, T=(o,l='en')=>Core.tx(o,l);
  const roleLabel=(id,l='en')=>Core.roleLabel(config,id,l), canonical=r=>Core.canonicalRole(r);
  const enabledRoles=()=> (config.roles||[]).filter(r=>r.enabled!==false);
  const value=a=>Core.normalizedValue(a);
  const validValues=arr=>(arr||[]).map(value).filter(Number.isFinite);
  const pct=(vals,p,d=1)=>Core.pct(vals,p,d);
  function download(name,content,type='application/json'){const b=new Blob([content],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);}
  function projectLine(){return `${config.project.code} – ${T(config.project.name)}`;}
  async function login(){const key=$('adminKey').value.trim();if(!key)return;const ok=await Cloud.login(key);if(!ok){alert('Invalid admin key.');return;}$('loginView').classList.add('hidden');$('adminApp').classList.remove('hidden');config=await Cloud.getConfig(window.DEFAULT_CONFIG);responses=await Cloud.getResponses();applyTheme();renderAll();setMode();}
  function setMode(){const cloud=Cloud.mode==='cloud';$('modeBadge').textContent=cloud?'● CLOUD / SHARED DATA':'● LOCAL PREVIEW';$('modeBadge').className=`status-badge ${cloud?'status-cloud':'status-local'}`;}
  function applyTheme(){document.documentElement.style.setProperty('--primary',config.theme?.primary||'#071a3a');document.documentElement.style.setProperty('--accent',config.theme?.accent||'#087a4a');$('adminProject').textContent=projectLine();}
  function tab(name){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));['dashboard','settings','questions','audience','data'].forEach(n=>$(`panel_${n}`).classList.toggle('hidden',n!==name));if(name==='dashboard')renderDashboard();if(name==='settings')renderSettings();if(name==='questions')renderQuestionBuilder();if(name==='audience')renderAudience();}
  function renderAll(){renderLanguageSelectors();renderRoleSelector();renderDashboardTabs();renderDashboard();renderSettings();renderQuestionBuilder();renderAudience();}
  function renderLanguageSelectors(){const options=(config.languages||[]).map(l=>`<option value="${E(l.code)}">${E(l.native)} — ${E(l.name)}</option>`).join('');['contentLang','questionLang','audienceLang'].forEach(id=>{const el=$(id);if(!el)return;const old=el.value;el.innerHTML=options;if([...el.options].some(o=>o.value===old))el.value=old;});}
  function renderRoleSelector(){const old=$('questionRole').value;$('questionRole').innerHTML=enabledRoles().map(r=>`<option value="${E(r.id)}">${E(roleLabel(r.id))}</option>`).join('');if([...$('questionRole').options].some(o=>o.value===old))$('questionRole').value=old;}
  function renderDashboardTabs(){
    const tabs=[{id:'Overall',label:'Overall'},...enabledRoles().map(r=>({id:r.id,label:roleLabel(r.id)}))];
    if(!tabs.some(x=>x.id===dashRole))dashRole='Overall';
    const host=$('dashboardTabs');
    host.innerHTML=tabs.map((x,i)=>`<button type="button" class="dash-tab ${x.id===dashRole?'active':''}" data-dash-index="${i}">${E(x.label)}</button>`).join('');
    host.querySelectorAll('[data-dash-index]').forEach(btn=>{
      btn.addEventListener('click',()=>{
        const idx=Number(btn.dataset.dashIndex);
        if(Number.isInteger(idx)&&tabs[idx]) selectDashRole(tabs[idx].id);
      });
    });
  }
  function selectDashRole(id){dashRole=id;renderDashboardTabs();renderDashboard();}
  function responseRole(r){return canonical(r?.role);}
  function scopedResponses(){return dashRole==='Overall'?responses:responses.filter(r=>responseRole(r)===dashRole);}
  function answerValues(rs){return (rs||[]).flatMap(r=>(r.answers||[]).map(value).filter(Number.isFinite));}
  function percentParts(vals){const n=vals.length;if(!n)return {bad:0,neutral:0,good:0};const bad=vals.filter(x=>x<=2).length/n*100,neutral=vals.filter(x=>x===3).length/n*100,good=100-bad-neutral;return {bad:Number(bad.toFixed(1)),neutral:Number(neutral.toFixed(1)),good:Number(good.toFixed(1))};}
  function stackHtml(vals){if(!vals.length)return '<div class="empty" style="padding:9px">No responses</div>';const p=percentParts(vals);const label=x=>x>=7?`${x.toFixed(1)}%`:'';return `<div class="stack"><div class="seg bad" style="width:${p.bad}%">${label(p.bad)}</div><div class="seg neutral" style="width:${p.neutral}%">${label(p.neutral)}</div><div class="seg good" style="width:${p.good}%">${label(p.good)}</div></div>`;}
  function renderDashboard(){
    const rs=scopedResponses(),vals=answerValues(rs),allComments=rs.flatMap(r=>(r.answers||[]).filter(a=>(a.comment||'').trim()));
    $('dResponses').textContent=rs.length;$('dFav').textContent=vals.length?`${pct(vals,x=>x>=4,1)}%`:'—';$('dNeutral').textContent=vals.length?`${pct(vals,x=>x===3,1)}%`:'—';$('dUnfav').textContent=vals.length?`${pct(vals,x=>x<=2,1)}%`:'—';$('dComments').textContent=allComments.length + rs.flatMap(r=>r.openAnswers||[]).filter(x=>(x.text||'').trim()).length;
    renderFactors(rs);renderRoleBreakdown();renderDivisions(rs);renderQuestions(rs);renderComments(rs);renderRecent(rs);
  }
  function renderFactors(rs){const groups={};Object.keys(config.factors||{}).forEach(f=>groups[f]=[]);rs.forEach(r=>(r.answers||[]).forEach(a=>{const v=value(a);if(Number.isFinite(v) && a.factor){(groups[a.factor]??=[]).push(v);}}));$('factorDashboard').innerHTML=Object.entries(groups).map(([f,vals])=>`<div class="stack-row"><div class="stack-label"><b>${E(T(config.factors[f]))}</b><span class="small">${vals.length?`${pct(vals,x=>x>=4,1)}% favourable`:'No data'}</span></div>${stackHtml(vals)}</div>`).join('');}
  function renderRoleBreakdown(){const groups={};enabledRoles().forEach(r=>groups[r.id]={values:[],responses:0});responses.forEach(r=>{const id=responseRole(r);if(!groups[id])return;groups[id].responses++;groups[id].values.push(...(r.answers||[]).map(value).filter(Number.isFinite));});$('roleDashboard').innerHTML=enabledRoles().map(r=>{const g=groups[r.id],p=g.values.length?pct(g.values,x=>x>=4,1):0;return `<div class="role-row"><div><b>${E(roleLabel(r.id))}</b></div><div class="bar"><i style="width:${p||0}%"></i></div><div class="bar-pct"><b>${g.values.length?p+'%':'—'}</b><span>${g.responses} resp.</span></div></div>`;}).join('');}
  function renderDivisions(rs){const groups={};rs.forEach(r=>{const k=r.division||'Not specified';groups[k]??={values:[],responses:0};groups[k].responses++;groups[k].values.push(...(r.answers||[]).map(value).filter(Number.isFinite));});const entries=Object.entries(groups).sort((a,b)=>b[1].responses-a[1].responses);$('divisionDashboard').innerHTML=entries.length?entries.map(([k,g])=>{const p=g.values.length?pct(g.values,x=>x>=4,1):0;return `<div class="division-row"><div>${E(k)}</div><div class="bar good"><i style="width:${p||0}%"></i></div><div class="bar-pct"><b>${g.values.length?p+'%':'—'}</b><span>${g.responses} resp.</span></div></div>`;}).join(''):'<div class="empty">No responses for this view.</div>';}
  function currentQuestionMap(){const map=new Map();enabledRoles().forEach(r=>(config.questions?.[r.id]||[]).forEach((q,i)=>map.set(`${r.id}::${q.id}`,{role:r.id,q,index:i,legacy:false})));return map;}
  function renderQuestions(rs){
    if(!rs.length){$('questionDashboard').innerHTML='<div class="empty">No responses yet.</div>';$('highlights').innerHTML='<div class="empty">No data yet.</div>';return;}
    const defs=currentQuestionMap(), groups=new Map();
    const ensure=(role,qid,answer)=>{const key=`${role}::${qid}`;if(groups.has(key))return groups.get(key);const d=defs.get(key);const g={key,role,qid,q:d?.q||null,index:d?.index??999,legacy:!d,values:[],sampleText:answer?.questionText||null,factor:answer?.factor||d?.q?.factor||''};groups.set(key,g);return g;};
    // Initialize current questions for selected questionnaire. For Overall, only questions that actually have data are displayed to keep it readable.
    if(dashRole!=='Overall'){(config.questions?.[dashRole]||[]).forEach((q,i)=>groups.set(`${dashRole}::${q.id}`,{key:`${dashRole}::${q.id}`,role:dashRole,q,index:i,legacy:false,values:[],sampleText:null,factor:q.factor}));}
    rs.forEach(r=>{const role=responseRole(r);(r.answers||[]).forEach(a=>{const qid=a.qid||`legacy_${Math.random()}`;const g=ensure(role,qid,a);const v=value(a);if(Number.isFinite(v))g.values.push(v);});});
    const list=[...groups.values()].filter(g=>dashRole!=='Overall'||g.values.length).sort((a,b)=>{const ra=enabledRoles().findIndex(r=>r.id===a.role),rb=enabledRoles().findIndex(r=>r.id===b.role);return ra-rb||a.index-b.index||a.qid.localeCompare(b.qid);});
    $('questionDashboard').innerHTML=list.length?list.map((g,i)=>{const title=g.q?T(g.q.text):T(g.sampleText);const roleBadge=dashRole==='Overall'?`<span class="pill">${E(roleLabel(g.role))}</span> `:'';return `<div class="question-result"><div class="q-title">${roleBadge}${g.legacy?'<span class="pill" style="background:#fff2d9;color:#77540d">Legacy</span> ':''}${E(title||g.qid)}</div>${stackHtml(g.values)}</div>`;}).join(''):'<div class="empty">No question data found.</div>';
    const withData=list.filter(g=>g.values.length).map(g=>({...g,...percentParts(g.values)}));if(!withData.length){$('highlights').innerHTML='<div class="empty">No data yet.</div>';return;}const best=[...withData].sort((a,b)=>b.good-a.good)[0],worst=[...withData].sort((a,b)=>b.bad-a.bad)[0];const title=g=>g.q?T(g.q.text):T(g.sampleText);$('highlights').innerHTML=`<div class="highlight good"><b>↑ Most favourable</b><p>${E(title(best)||best.qid)}</p><strong>${best.good.toFixed(1)}% favourable</strong></div><div class="highlight bad" style="margin-top:9px"><b>↓ Most unfavourable</b><p>${E(title(worst)||worst.qid)}</p><strong>${worst.bad.toFixed(1)}% unfavourable</strong></div>`;
  }
  function renderComments(rs){const items=[];rs.forEach(r=>{const role=responseRole(r);(r.answers||[]).forEach(a=>{if((a.comment||'').trim())items.push({time:r.timestamp,role,division:r.division,kind:'Question comment',question:T(a.questionText),text:a.comment,rating:a.value});});(r.openAnswers||[]).forEach(o=>{if((o.text||'').trim())items.push({time:r.timestamp,role,division:r.division,kind:'Open feedback',question:T(o.questionText),text:o.text,rating:null});});});items.sort((a,b)=>String(b.time).localeCompare(String(a.time)));$('commentsFeed').innerHTML=items.length?items.slice(0,80).map(x=>`<div class="comment-item"><div class="small">${E(roleLabel(x.role))} • ${E(x.division||'')} • ${x.time?new Date(x.time).toLocaleDateString():''}${x.rating?` • Rating ${x.rating}/5`:''}</div><b>${E(x.kind)}${x.question?` — ${E(x.question)}`:''}</b><div style="margin-top:5px">${E(x.text)}</div></div>`).join(''):'<div class="empty">No comments or justifications in this view.</div>';}
  function renderRecent(rs){const x=[...rs].sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp))).slice(0,15);$('recentResponses').innerHTML=x.length?`<div style="overflow:auto"><table class="table"><thead><tr><th>Date</th><th>Role</th><th>Division</th><th>Company</th><th>Language</th><th>Favourable</th></tr></thead><tbody>${x.map(r=>{const vals=(r.answers||[]).map(value).filter(Number.isFinite);return `<tr><td>${r.timestamp?new Date(r.timestamp).toLocaleString():''}</td><td>${E(roleLabel(responseRole(r)))}</td><td>${E(r.division||'')}</td><td>${E(r.company||'')}</td><td>${E(r.language||'')}</td><td>${vals.length?pct(vals,v=>v>=4,1)+'%':'—'}</td></tr>`;}).join('')}</tbody></table></div>`:'<div class="empty">No responses.</div>';}
  async function refreshResponses(){try{responses=await Cloud.getResponses();renderDashboard();}catch(e){alert('Could not refresh responses: '+e.message);}}
  function renderSettings(){const l=$('contentLang').value||'en';$('projectCode').value=config.project.code||'';$('projectName').value=T(config.project.name,l);$('surveyNameEdit').value=T(config.project.surveyName,l);$('surveySubtitleEdit').value=T(config.project.subtitle,l);$('primaryColor').value=config.theme?.primary||'#071a3a';$('accentColor').value=config.theme?.accent||'#087a4a';$('logoEditors').innerHTML=(config.logos||[]).map((x,i)=>`<div class="logo-editor"><img src="${E(x.src)}"><div style="font-weight:850;margin:7px 0">${E(x.name)}</div><label class="small"><input type="checkbox" ${x.enabled!==false?'checked':''} onchange="Admin.toggleLogo(${i},this.checked)"> Enabled</label><div class="inline-actions" style="justify-content:center;margin-top:7px"><label class="btn btn-secondary" style="font-size:10px;padding:6px 8px">Replace<input type="file" accept="image/*" hidden onchange="Admin.replaceLogo(${i},this.files[0]);this.value=''"></label><button class="btn btn-danger" style="font-size:10px;padding:6px 8px" onclick="Admin.deleteLogo(${i})">Delete</button></div></div>`).join('');}
  function setProjectCode(v){config.project.code=v;}function setProjectText(k,v){const l=$('contentLang').value||'en';config.project[k][l]=v;}function setTheme(k,v){config.theme[k]=v;applyTheme();}
  function fileData(file){return new Promise((res,rej)=>{if(!file)return rej(new Error('No file selected'));if(file.size>1500000)return rej(new Error('Please use an image smaller than 1.5 MB.'));const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});}
  async function addLogo(file){try{config.logos.push({id:`logo_${Date.now()}`,name:file.name,src:await fileData(file),enabled:true});renderSettings();}catch(e){alert(e.message);}}async function replaceLogo(i,file){try{config.logos[i].src=await fileData(file);config.logos[i].name=file.name;renderSettings();}catch(e){alert(e.message);}}function toggleLogo(i,v){config.logos[i].enabled=v;}function deleteLogo(i){if(confirm('Delete this logo?')){config.logos.splice(i,1);renderSettings();}}
  async function saveConfig(){try{config.version=7;await Cloud.saveConfig(config);applyTheme();alert('Changes saved successfully.');renderAll();}catch(e){alert('Could not save configuration: '+e.message);}}
  function renderQuestionBuilder(){const role=$('questionRole').value||enabledRoles()[0]?.id,l=$('questionLang').value||'en',qs=config.questions?.[role]||[];$('questionEditors').innerHTML=qs.map((q,i)=>`<div class="question-editor"><div class="question-editor-head"><div style="display:flex;gap:8px;align-items:center"><div class="qnum">${i+1}</div><b>${E(q.id)}</b></div><div class="inline-actions"><button class="btn btn-secondary" style="padding:6px 8px" onclick="Admin.moveQuestion(${i},-1)">↑</button><button class="btn btn-secondary" style="padding:6px 8px" onclick="Admin.moveQuestion(${i},1)">↓</button><button class="btn btn-secondary" style="padding:6px 8px" onclick="Admin.duplicateQuestion(${i})">Duplicate</button><button class="btn btn-danger" style="padding:6px 8px" onclick="Admin.deleteQuestion(${i})">Delete</button></div></div><div class="qedit-grid"><div class="field"><label>Factor</label><select onchange="Admin.setQuestion(${i},'factor',this.value)">${Object.keys(config.factors||{}).map(f=>`<option value="${E(f)}" ${f===q.factor?'selected':''}>${E(T(config.factors[f],l))}</option>`).join('')}</select></div><div class="field"><label>Question wording — ${E(l.toUpperCase())}</label><textarea rows="3" oninput="Admin.setQuestionText(${i},${JSON.stringify(l)},this.value)">${E(T(q.text,l))}</textarea></div><label style="font-size:11px;padding-top:27px"><input type="checkbox" ${q.negative?'checked':''} onchange="Admin.setQuestion(${i},'negative',this.checked)"> Negative statement / reverse scoring</label></div></div>`).join('')||'<div class="empty">No questions in this questionnaire.</div>';renderOpenEditors(l);}
  function setQuestion(i,k,v){const role=$('questionRole').value;config.questions[role][i][k]=v;}function setQuestionText(i,l,v){const role=$('questionRole').value;config.questions[role][i].text[l]=v;}function addQuestion(){const role=$('questionRole').value,text={};(config.languages||[]).forEach(x=>text[x.code]=x.code==='en'?'Enter the new question here.':'');config.questions[role].push({id:`q_${Date.now()}`,factor:'org',negative:false,text});renderQuestionBuilder();}function moveQuestion(i,d){const role=$('questionRole').value,a=config.questions[role],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];renderQuestionBuilder();}function duplicateQuestion(i){const role=$('questionRole').value,q=Core.clone(config.questions[role][i]);q.id=`${q.id}_copy_${Date.now()}`;config.questions[role].splice(i+1,0,q);renderQuestionBuilder();}function deleteQuestion(i){if(confirm('Delete this question from future surveys?')){config.questions[$('questionRole').value].splice(i,1);renderQuestionBuilder();}}
  function renderOpenEditors(l){$('openEditors').innerHTML=(config.openQuestions||[]).map((q,i)=>`<div class="question-editor"><div class="question-editor-head"><b>${E(q.id)}</b><button class="btn btn-danger" style="padding:6px 8px" onclick="Admin.deleteOpen(${i})">Delete</button></div><div class="field"><label>Open question — ${E(l.toUpperCase())}</label><textarea rows="3" oninput="Admin.setOpen(${i},${JSON.stringify(l)},this.value)">${E(T(q,l))}</textarea></div></div>`).join('');}function addOpenQuestion(){const q={id:`open_${Date.now()}`};(config.languages||[]).forEach(x=>q[x.code]=x.code==='en'?'Enter the new open question here.':'');config.openQuestions.push(q);renderQuestionBuilder();}function setOpen(i,l,v){config.openQuestions[i][l]=v;}function deleteOpen(i){if(confirm('Delete this open question?')){config.openQuestions.splice(i,1);renderQuestionBuilder();}}
  function renderAudience(){const l=$('audienceLang').value||'en';$('languageEditors').innerHTML=(config.languages||[]).map((x,i)=>`<div class="question-editor" style="padding:10px"><div class="grid2"><div class="field"><label>Native label</label><input value="${E(x.native)}" oninput="Admin.setLanguage(${i},'native',this.value)"></div><label style="padding-top:27px"><input type="checkbox" ${x.enabled!==false?'checked':''} onchange="Admin.setLanguage(${i},'enabled',this.checked)"> Enabled — ${E(x.name)}</label></div></div>`).join('');$('roleEditors').innerHTML=enabledRoles().map((r,i)=>{const actual=(config.roles||[]).findIndex(x=>x.id===r.id);return `<div class="question-editor" style="padding:10px"><div class="grid2"><div class="field"><label>Role name — ${E(l.toUpperCase())}</label><input value="${E(T(r.text,l))}" oninput="Admin.setRoleText(${actual},'text',${JSON.stringify(l)},this.value)"></div><div class="field"><label>Description — ${E(l.toUpperCase())}</label><input value="${E(T(r.description,l))}" oninput="Admin.setRoleText(${actual},'description',${JSON.stringify(l)},this.value)"></div></div><div class="grid2" style="margin-top:8px"><div class="field"><label>Icon / emoji</label><input value="${E(r.icon||'')}" oninput="Admin.setRole(${actual},'icon',this.value)"></div><label style="padding-top:27px"><input type="checkbox" ${r.enabled!==false?'checked':''} onchange="Admin.setRole(${actual},'enabled',this.checked)"> Enabled</label></div></div>`;}).join('');$('divisionEditor').value=(config.divisions||[]).join('\n');}
  function setLanguage(i,k,v){config.languages[i][k]=v;}function setRole(i,k,v){config.roles[i][k]=v;}function setRoleText(i,k,l,v){config.roles[i][k][l]=v;}function setDivisions(v){config.divisions=v.split('\n').map(x=>x.trim()).filter(Boolean);}
  async function resetResponses(){if(!confirm('Delete ALL submitted responses and reset the dashboard to zero?'))return;if(!confirm('Final confirmation: this cannot be undone unless you exported a backup.'))return;try{await Cloud.resetResponses();responses=[];renderDashboard();alert('Dashboard reset completed.');}catch(e){alert('Reset failed: '+e.message);}}
  function exportConfig(){download('HAJR_Safety_Climate_V7_Config.json',JSON.stringify(config,null,2));}function exportJSON(){download('HAJR_Safety_Climate_V7_Results.json',JSON.stringify(responses,null,2));}
  function exportCSV(){const rows=[['Timestamp','Role','Division','Company','Area','Language','Question ID','Factor','Rating','Normalised rating','Comment']];responses.forEach(r=>(r.answers||[]).forEach(a=>rows.push([r.timestamp,responseRole(r),r.division,r.company,r.area,r.language,a.qid,a.factor,a.value,value(a),a.comment||''])));const csv=rows.map(row=>row.map(x=>`"${String(x??'').replaceAll('"','""')}"`).join(',')).join('\n');download('HAJR_Safety_Climate_V7_Results.csv',csv,'text/csv');}
  async function changePin(){const p=$('newLocalPin').value.trim();if(p.length<4){alert('Use at least 4 characters.');return;}await Cloud.changeLocalPin(p);$('newLocalPin').value='';alert('Local preview PIN changed.');}
  return {login,tab,selectDashRole,refreshResponses,renderSettings,setProjectCode,setProjectText,setTheme,addLogo,replaceLogo,toggleLogo,deleteLogo,saveConfig,renderQuestionBuilder,setQuestion,setQuestionText,addQuestion,moveQuestion,duplicateQuestion,deleteQuestion,addOpenQuestion,setOpen,deleteOpen,renderAudience,setLanguage,setRole,setRoleText,setDivisions,resetResponses,exportConfig,exportJSON,exportCSV,changePin};
})();
if(sessionStorage.getItem('hajr_admin_key')){document.getElementById('adminKey').value=sessionStorage.getItem('hajr_admin_key');Admin.login();}
